stages_optimisation:
  opt1:
    file: optimise.py
    entrypoint: optimise
    trials: 600
    study:
      name: kernel_study          
    sampler:                                 # optional; advanced, usually not needed; default is tpe with its default args
      name: tpe                              # tree-parzen estimator
      args:                                  # see https://optuna.readthedocs.io/en/stable/reference/samplers/generated/optuna.samplers.TPESampler.html for possible arguments of TPE sampler
        constant_liar: false
        n_startup_trials: 100
